--- #YAML:1.0
name:                Log-Fine
version:             0.531
abstract:            Yet another logging framework
license:             bsd
author:              
    - Christopher M. Fuhrman <cfuhrman@panix.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Sys::Syslog:                   0.13
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
